export const FETCH_QUESTION_REQUEST = 'FETCH_QUESTION_REQUEST';
export const FETCH_QUESTION_SUCCESS = 'FETCH_QUESTION_SUCCESS';
export const FETCH_QUESTION_FAILURE = 'FETCH_QUESTION_FAILURE';
export const TEST_STARTED = 'TEST_STARTED';
export const ANSWER_CLICKED = 'ANSWER_CLICKED';
export const QUESTION_NEXT = 'QUESTION_NEXT';
export const TEST_RESULT = 'TEST_RESULT';
export const TEST_AGAIN = 'TEST_AGAIN';
